on:
  push:
    branches:
      - '0.8-debug'
  pull_request:
      types: [closed]
      branches:
          - '0.8-debug'
name: Bundle and Publish Sources
jobs:
  build:
    name: Bundle and Publish Sources
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install
      - run: npm run bundle -- --folder='0.8-debug'
      - run: npx typedoc -out bundles/docs
        continue-on-error: true

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
            branch: gh-pages
            folder: bundles
